### ISSUE TITLE
wew

### ISSUE THREAD

**Issue by karthikkm007** [ghostrider-reborn/scripts#1]
https://github.com/ghostrider-reborn/scripts/blob/b14af6b2943eef7e06760837a5442ad2240b2c62/gcloud_setup.sh#L81

There is a small derp boi

**Comment by adithya2306** [comment]
> [scripts/gcloud_setup.sh](https://github.com/ghostrider-reborn/scripts/blob/b14af6b2943eef7e06760837a5442ad2240b2c62/gcloud_setup.sh#L81)
> 
> Line 81 in [b14af6b](/ghostrider-reborn/scripts/commit/b14af6b2943eef7e06760837a5442ad2240b2c62)
> 
>  echo -e "\nALL DONE. Now sync sauces & start baking!\n" 
> There is a small derp boi

Thx bru fixing it
